# Generated by Django 4.1 on 2022-08-08 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProcessoAdministrativoLebre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=16)),
                ('nome_pessoa', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_abertura_processo', models.DateField(default=datetime.datetime.now)),
                ('codigo_licenca', models.CharField(max_length=50)),
                ('data_emissao_licenca', models.DateField(blank=True, null=True)),
                ('data_validade_licenca', models.DateField(blank=True, null=True)),
                ('tipo_licenca', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_codigo_licenca', models.CharField(blank=True, max_length=2, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_endereco_instalacao', models.CharField(blank=True, max_length=100, null=True)),
                ('atividade', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
