# Generated by Django 4.1 on 2022-08-21 05:45

import datetime
from django.db import migrations, models
import lebre.models


class Migration(migrations.Migration):

    dependencies = [
        ('lebre', '0002_alter_viewprocessoadministrativolebre_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField()),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_despacho', models.DateField(default=datetime.datetime.now)),
                ('data_conclusao', models.DateField(default=datetime.datetime.now)),
                ('despacho', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'view depacho',
                'verbose_name_plural': 'view despachos',
                'db_table': 'tb_view_despacho',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ViewNotificacoesLebre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField()),
                ('codigo_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('data_emissao', models.DateField(default=datetime.datetime.now)),
                ('tipo_aviso', models.CharField(max_length=100)),
                ('descricao_assunto', models.CharField(max_length=150)),
                ('descricao_sigla', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'view notificação',
                'verbose_name_plural': 'view notificações',
                'db_table': 'tb_view_notificacao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ViewPareceresArquivosLebre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField()),
                ('descricao_documento', models.CharField(max_length=150)),
                ('descricao_link', models.FileField(upload_to=lebre.models.upload_pareceres_path)),
                ('data_emissao', models.DateField(default=datetime.datetime.now)),
                ('descricao_usuario', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'view pareceres e arquivos',
                'verbose_name_plural': 'view pareceres arquivos',
                'db_table': 'tb_view_pareceres_arquivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ViewTramitacaoLebre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField()),
                ('orgao_origem', models.CharField(max_length=6)),
                ('data_remessa', models.DateField(default=datetime.datetime.now)),
                ('setor_destino', models.CharField(max_length=100)),
                ('data_recebimento', models.DateField(default=datetime.datetime.now)),
                ('despacho', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'view tramitacao',
                'verbose_name_plural': 'view tramitacoes',
                'db_table': 'tb_view_tramitacao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ViewVistoriaLebre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField()),
                ('numero_vistoria', models.CharField(max_length=100)),
                ('data_vistoria', models.DateField(default=datetime.datetime.now)),
                ('descricao', models.CharField(max_length=150)),
                ('id_vistoria', models.IntegerField()),
            ],
            options={
                'verbose_name': 'view vistoria',
                'verbose_name_plural': 'view vistorias',
                'db_table': 'tb_view_vistoria',
                'ordering': ['id'],
            },
        ),
    ]
