# Generated by Django 4.1 on 2022-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lebre', '0003_viewdespacho_viewnotificacoeslebre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewtramitacaolebre',
            name='tipo',
            field=models.CharField(default=1998, max_length=100),
            preserve_default=False,
        ),
    ]
