# Generated by Django 4.1 on 2022-08-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lebre', '0004_viewtramitacaolebre_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewDespacho',
            new_name='ViewDespachoLebre',
        ),
    ]
