# Generated by Django 4.1 on 2022-08-08 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProcessoAdministrativoCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=100)),
                ('descricao_servico', models.TextField()),
                ('data_abertura', models.DateField(default=datetime.datetime.now)),
                ('sigla_servico', models.CharField(max_length=4)),
                ('descricao_atividade', models.TextField(blank=True, null=True)),
                ('sigla_setor', models.CharField(blank=True, max_length=4, null=True)),
                ('nome_pessoa_fisica', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pessoa_juridica', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=16, null=True)),
                ('pessoa_fisica_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('pessoa_juridica_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_licenca', models.CharField(max_length=100)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_fim_validade', models.DateField(blank=True, null=True)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
            ],
        ),
    ]
