# Generated by Django 4.1 on 2022-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0003_alter_viewtramitacaocorporativo_data_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewtramitacaocorporativo',
            name='id_processo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
