# Generated by Django 4.1 on 2022-08-18 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0004_viewtramitacaocorporativo_id_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDocumentosPad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_processo', models.IntegerField(blank=True, null=True)),
                ('numero_processo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('codigo_documento', models.CharField(max_length=100)),
                ('data_assinatura', models.DateField(default=datetime.datetime.now)),
                ('doc_name', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_view_documento',
                'ordering': ['id'],
            },
        ),
    ]
