# Generated by Django 4.1 on 2022-08-19 03:16

from django.db import migrations, models
import pad.models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0005_viewdocumentospad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewdocumentospad',
            options={'ordering': ['id'], 'verbose_name': 'view documento', 'verbose_name_plural': 'view documentos'},
        ),
        migrations.AddField(
            model_name='viewdocumentospad',
            name='documento',
            field=models.FileField(default=2004, upload_to=pad.models.upload_documento_path),
            preserve_default=False,
        ),
    ]
