# Generated by Django 4.1 on 2022-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0006_alter_viewdocumentospad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewtramitacaocorporativo',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AlterField(
            model_name='viewdocumentospad',
            name='id_processo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='viewtramitacaocorporativo',
            name='id_processo',
            field=models.IntegerField(default=1998),
            preserve_default=False,
        ),
    ]
