# Generated by Django 4.1 on 2022-08-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0007_alter_viewtramitacaocorporativo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewtramitacaocorporativo',
            table='tb_view_tramitacao_corporativo',
        ),
    ]
